<?php
// Publish 6 new SEO page types (4 comparison + 2 region hubs) + RankMath meta. Run via wp eval-file.
// slug => [title, summary, body_html, money-slug-or-empty, anchor, meta-description, focus-keyword]
$g = [

// ---------- A) COMPARISON PAGES ----------
'evisa-vs-visa-on-arrival-uk' => ['eVisa vs Visa on Arrival: Which Is Better for UK Travellers',
 'For many countries UK travellers can choose between an eVisa, applied for online before departure, and a visa on arrival (VOA) bought at the airport. An eVisa means you land already approved and skip a counter queue; a VOA suits last-minute trips but means paying and queueing after you land. The best choice depends on the country, your timing and how much certainty you want. We are an independent service that helps you prepare and check an eVisa application — not a government website, and our service fee is separate from the government visa fee.',
 '<h2>How they compare</h2><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%"><thead><tr style="background:#EEF3FA"><th align="left">Feature</th><th align="left">eVisa (online, in advance)</th><th align="left">Visa on arrival</th></tr></thead><tbody><tr><td>When you apply</td><td>Days before travel, online</td><td>At the airport after you land</td></tr><tr><td>Certainty</td><td>You arrive already approved</td><td>Subject to counter queues and stock</td></tr><tr><td>Best for</td><td>Planned trips, peace of mind</td><td>Last-minute, spontaneous travel</td></tr><tr><td>Payment</td><td>Online, by card</td><td>Often cash, sometimes only major currencies</td></tr></tbody></table><p>Whichever route applies, your passport should typically be valid for at least 6 months beyond arrival, and you should always apply via the official government portal. Rules differ by destination and change often, so check the latest requirements before you book.</p><h3>FAQ</h3><p><strong>Is one faster than the other?</strong> An eVisa avoids the arrivals queue, but processing time is set by the government, not us. Any express tier we offer speeds up <em>our</em> handling only — it does not make the government decide faster or guarantee approval. <strong>Which is cheaper?</strong> Fees vary by country; compare the official fee for each route. <strong>Can I always pick?</strong> No — some countries only offer one route, so check first.</p>',
 '','UK eVisa & travel authorisation help','How eVisas and visa on arrival differ for UK travellers, and which suits your trip — applied for online or at the airport.','evisa vs visa on arrival uk'],

'eta-vs-evisa-vs-visa-uk' => ['ETA vs eVisa vs Visa: What UK Travellers Need to Know',
 'UK travellers meet three main entry documents abroad: an ETA (electronic travel authorisation, such as a US ESTA, Canada eTA or NZeTA), an eVisa, and a traditional visa. An ETA is a quick pre-screening linked to your passport for visa-exempt visits; an eVisa is an actual visa issued electronically; a traditional visa is granted by a consulate or on arrival. Knowing which your destination uses avoids surprises at the airport. We are an independent service that helps you prepare and check applications — not a government website, and our service fee is separate from any government fee.',
 '<h2>How they compare</h2><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%"><thead><tr style="background:#EEF3FA"><th align="left">Type</th><th align="left">What it is</th><th align="left">Examples</th></tr></thead><tbody><tr><td>ETA / authorisation</td><td>A pre-travel check linked to your passport for visa-exempt travellers — not a visa and not a physical document</td><td>US ESTA, Canada eTA, NZeTA, ETIAS (forthcoming)</td></tr><tr><td>eVisa</td><td>An actual visa issued electronically and emailed to you to print</td><td>India, Egypt, Turkey, Vietnam (longer stays)</td></tr><tr><td>Traditional visa</td><td>A visa granted by a consulate or at the border, often stamped in the passport</td><td>Consular tourist/business visas; visa on arrival</td></tr></tbody></table><p>An authorisation like an ESTA is tied to your passport, not printed in it, and never guarantees entry — a border officer still decides. Passport validity rules differ (often 6+ months), so check the latest requirements and use the official portal for each country.</p><h3>FAQ</h3><p><strong>Is an ESTA a visa?</strong> No — it is an authorisation linked to your passport, not a visa or a document you carry. <strong>Do I always need one of these?</strong> No — some destinations are visa-free for UK citizens; check before you travel. <strong>Does express get me approved faster?</strong> Any express tier speeds up <em>our</em> handling only, never the government decision.</p>',
 '','UK eVisa & travel authorisation help','ETA vs eVisa vs traditional visa explained for UK travellers — what each is, examples, and how to tell which you need.','eta vs evisa vs visa uk'],

'single-vs-multiple-entry-visas-uk' => ['Single vs Multiple Entry Visas Explained (UK Travellers)',
 'A single-entry visa lets you enter a country once; if you leave, it is used up even if time remains. A multiple-entry visa lets you come and go repeatedly within its validity. For UK travellers, the right choice depends on your itinerary — particularly side trips to neighbouring countries or regional hopping. Picking the wrong type can mean buying another visa. We are an independent service that helps you prepare and check the application — not a government website, and our service fee is separate from the government visa fee.',
 '<h2>How they compare</h2><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%"><thead><tr style="background:#EEF3FA"><th align="left">Feature</th><th align="left">Single entry</th><th align="left">Multiple entry</th></tr></thead><tbody><tr><td>Entries allowed</td><td>One — used up when you leave</td><td>Many, within the validity period</td></tr><tr><td>Best for</td><td>One straight visit, no side trips</td><td>Regional hopping, repeat visits</td></tr><tr><td>Side trips</td><td>Re-entry needs a new visa</td><td>Re-enter freely while valid</td></tr><tr><td>Cost</td><td>Usually lower per visa</td><td>Often higher, but better value if you re-enter</td></tr></tbody></table><p>Always check the visa label or approval for the exact number of entries and the validity dates, and remember that a visa or authorisation never guarantees entry — a border officer decides. Rules and fees vary by country and change often, so confirm the latest before you apply via the official portal.</p><h3>FAQ</h3><p><strong>If I take a day trip to a neighbouring country, do I re-enter on a single-entry visa?</strong> No — leaving generally uses it up; you would need a multiple-entry visa or a fresh one. <strong>Is multiple entry always worth it?</strong> Only if you plan to re-enter; otherwise single entry is usually cheaper. <strong>Does express change my entry count?</strong> No — express speeds up <em>our</em> handling only and does not change the visa type or government decision.</p>',
 '','UK eVisa & travel authorisation help','Single vs multiple entry visas explained for UK travellers — entries allowed, when each suits your trip, and how to choose.','single vs multiple entry visas uk'],

'tourist-vs-business-visa-uk' => ['Tourist vs Business Visa: Which Do UK Travellers Need',
 'A tourist visa covers holidays, sightseeing and visiting friends or family, while a business visa covers meetings, conferences, negotiations and similar short work-related visits. For UK travellers the right type depends on the purpose of your trip — and using the wrong one can cause problems at the border. Neither type normally allows paid local employment. We are an independent service that helps you prepare and check the application — not a government website, and our service fee is separate from the government visa fee.',
 '<h2>How they compare</h2><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%"><thead><tr style="background:#EEF3FA"><th align="left">Feature</th><th align="left">Tourist visa</th><th align="left">Business visa</th></tr></thead><tbody><tr><td>Purpose</td><td>Holidays, sightseeing, visiting family</td><td>Meetings, conferences, negotiations</td></tr><tr><td>Typical activities</td><td>Leisure travel only</td><td>Business discussions, events, site visits</td></tr><tr><td>Paid work</td><td>Not permitted</td><td>Usually not permitted — needs a work visa</td></tr><tr><td>Documents</td><td>Itinerary, accommodation</td><td>Often an invitation letter from the host company</td></tr></tbody></table><p>Choose the type that matches your real reason for travelling. If any part of the trip involves paid local employment, you typically need a separate work visa, not a tourist or business one. Requirements and permitted activities vary by country and change, so check the latest official guidance before you apply via the official portal.</p><h3>FAQ</h3><p><strong>Can I attend a conference on a tourist visa?</strong> Often you need a business visa for work-related events — check the destination rules. <strong>Can I work on a business visa?</strong> Usually not; paid employment generally needs a work visa. <strong>Does express change which visa I get?</strong> No — express speeds up <em>our</em> handling only, not the visa category or the government decision.</p>',
 '','UK eVisa & travel authorisation help','Tourist vs business visa for UK travellers — what each covers, typical documents, and how to choose the right one.','tourist vs business visa uk'],

// ---------- B) REGION HUB PAGES ----------
'southeast-asia-visa-guide-uk' => ['Southeast Asia Visa Guide for UK Travellers',
 'Southeast Asia is one of the most popular regions for UK travellers, and entry rules vary widely from country to country — some are visa-free, some use a visa on arrival, and others require an eVisa applied for in advance. This hub links our country-by-country guides so you can check what you need for Thailand, Vietnam, Cambodia and Indonesia (Bali) before you book. We are an independent service that helps you prepare and check applications — not a government website, and our service fee is separate from any government visa fee.',
 '<h2>Country guides</h2><ul><li><a href="/ukvisa/thailand-visa-exemption-uk/">Thailand visa exemption (60-day rule) for UK tourists</a></li><li><a href="/ukvisa/thailand-tdac-how-to/">Thailand Digital Arrival Card (TDAC): how to complete it</a></li><li><a href="/ukvisa/best-time-to-visit-thailand/">Best time to visit Thailand</a></li><li><a href="/ukvisa/vietnam-visa-free-vs-evisa/">Vietnam visa-free vs e-Visa for UK travellers</a></li><li><a href="/ukvisa/is-vietnam-safe-for-tourists/">Is Vietnam safe for tourists?</a></li><li><a href="/ukvisa/cambodia-evisa-for-uk-citizens/">Cambodia e-Visa for UK citizens: how to apply</a></li><li><a href="/ukvisa/bali-indonesia-voa-vs-evoa-uk/">Indonesia (Bali) visa on arrival vs e-VOA for UK travellers</a></li></ul><h2>What to know before you go</h2><p>Entry routes across the region range from visa-free stays to visa on arrival and eVisas, and the exact allowance, fees and required documents differ by country and change regularly. As a rule of thumb, keep your passport valid for at least 6 months beyond arrival, carry onward-travel proof, and always apply through the official government portal for each country. Any express tier we offer speeds up <em>our</em> preparation and checks only — it does not make a government decide faster or guarantee approval.</p><h3>FAQ</h3><p><strong>Is one visa valid for all of Southeast Asia?</strong> No — each country has its own rules; check every destination separately. <strong>Are these countries visa-free for UK citizens?</strong> It varies; some are visa-free, others need an eVisa or visa on arrival. <strong>When should I apply?</strong> Well ahead of travel, as processing times are not guaranteed.</p>',
 'thailand','Thailand travel & visa guide','Southeast Asia visa guide for UK travellers — entry rules and country guides for Thailand, Vietnam, Cambodia and Bali.','southeast asia visa guide uk'],

'middle-east-evisa-hub-uk' => ['Middle East eVisa Hub for UK Travellers',
 'The Middle East draws UK travellers for both leisure and business, and entry rules differ markedly between countries — some require a tourist eVisa applied for online, others have offered visa-free short stays at times. This hub links our country guides for Saudi Arabia, Oman and Egypt, plus practical travel tips, so you can check what you need before booking. We are an independent service that helps you prepare and check applications — not a government website, and our service fee is separate from any government visa fee.',
 '<h2>Country guides</h2><ul><li><a href="/ukvisa/saudi-arabia-tourist-evisa-uk/">Saudi Arabia tourist eVisa for UK citizens</a></li><li><a href="/ukvisa/oman-evisa-for-uk-travellers/">Oman eVisa for UK travellers: what to know</a></li><li><a href="/ukvisa/egypt-evisa-vs-visa-on-arrival/">Egypt e-Visa vs visa on arrival for UK travellers</a></li><li><a href="/ukvisa/best-time-to-visit-egypt/">Best time to visit Egypt</a></li><li><a href="/ukvisa/dubai-dress-code-for-tourists/">Dubai dress code for tourists</a></li></ul><h2>What to know before you go</h2><p>Across the region, some countries issue a tourist eVisa online, some sell a visa on arrival, and entry rules have changed in recent years — including periods of visa-free short stays for certain visitors. Confirm whether you need a visa or eVisa for your specific destination and dates before booking. Keep your passport valid for at least 6 months beyond arrival, respect local dress and conduct customs, and always apply via the official government portal. Any express tier we offer speeds up <em>our</em> handling only — it does not make a government decide faster or guarantee approval.</p><h3>FAQ</h3><p><strong>Does one eVisa cover the whole Middle East?</strong> No — each country has its own system; check each separately. <strong>Are some countries visa-free for UK citizens?</strong> Sometimes, and rules change — always confirm the latest before you travel. <strong>When should I apply?</strong> Ahead of travel, since processing times are not guaranteed.</p>',
 'egypt','Egypt travel & visa guide','Middle East eVisa hub for UK travellers — country guides and tips for Saudi Arabia, Oman, Egypt and the UAE.','middle east evisa hub uk'],
];
foreach ( $g as $slug => $d ) {
	$money = $d[3] !== '' ? '/ukvisa/' . $d[3] . '/' : '/ukvisa/';
	$content = '<p style="font-size:18px;font-weight:500;background:#EEF3FA;padding:14px 18px;border-radius:8px">' . $d[1] . '</p>' . $d[2]
		. '<p>For current entry rules, fees and application help, see our <a href="' . $money . '">' . $d[4] . '</a>. Independent service — not a government website; our service fee is separate from the government fee.</p>';
	$e = get_page_by_path( $slug, OBJECT, 'page' );
	$arr = [ 'post_type' => 'page', 'post_name' => $slug, 'post_title' => $d[0], 'post_content' => $content, 'post_status' => 'publish' ];
	if ( $e ) { $arr['ID'] = $e->ID; $id = $e->ID; wp_update_post( $arr ); } else { $id = wp_insert_post( $arr ); }
	update_post_meta( $id, 'rank_math_title', $d[0] );
	update_post_meta( $id, 'rank_math_description', $d[5] );
	update_post_meta( $id, 'rank_math_focus_keyword', $d[6] );
	echo "$slug -> #$id\n";
}
