<?php
// Publish 8 more backlog guides + meta. Run via wp eval-file. slug => [title, answer, body, money-slug, anchor, meta, focus]
$g = [
'thailand-visa-exemption-uk' => ['Thailand Visa Exemption for UK Tourists: the 60-Day Rule',
 'British passport holders can visit Thailand without a visa under the exemption scheme, currently allowing stays of up to 60 days per entry for tourism. You arrive with a valid passport and onward-travel proof — no advance visa. The exemption can usually be extended once at a local immigration office.',
 '<h2>How it works</h2><p>Immigration grants entry under the exemption (not a stamped visa) for tourism/family visits. Passport valid 6+ months; officers may ask for onward ticket + accommodation. 60 days counted from arrival; policy can change.</p><h2>Extending</h2><p>You can usually apply for one extension at a Thai immigration office for extra days (fee applies). Track your permitted-until date; overstaying carries fines.</p><h3>FAQ</h3><p><strong>Visa needed?</strong> No, visa-free up to 60 days. <strong>Extend it?</strong> Yes, once at immigration.</p>',
 'thailand','Thailand travel guide','How the Thailand visa exemption works for UK tourists — the 60-day stay, entry conditions and extensions.','thailand visa exemption uk'],
'thailand-tdac-how-to' => ['Thailand Digital Arrival Card (TDAC): How to Complete It',
 'The Thailand Digital Arrival Card (TDAC) is a free online form most visitors, including UK travellers, must complete before arriving. It replaces the paper arrival card. Fill it in the days before your trip with personal, passport and accommodation details, and show the confirmation at immigration.',
 '<h2>What it is</h2><p>A free electronic immigration declaration (not a visa). Submit via the official Thai government portal within the days before arrival; save the confirmation.</p><h2>Steps</h2><p>Enter passport details exactly, add flight + accommodation address, review, submit, save/print the confirmation. One card per person incl. children.</p><h3>FAQ</h3><p><strong>Free?</strong> Yes — use only the official portal. <strong>When?</strong> Shortly before travel, within the official window.</p>',
 'thailand','Thailand entry guide','A step-by-step guide to completing the free Thailand Digital Arrival Card (TDAC) online before you travel.','thailand digital arrival card'],
'egypt-evisa-vs-visa-on-arrival' => ['Egypt e-Visa vs Visa on Arrival for UK Travellers',
 'UK travellers need a visa for Egypt and have two options: an e-Visa applied for online before departure, or a visa on arrival bought at the airport. The e-Visa means you arrive already sorted; visa on arrival is purchased at a bank kiosk after landing. Both are tourist routes for short stays.',
 '<h2>e-Visa</h2><p>Apply online via the official portal, pay, receive an approved e-Visa by email to print. Certainty + skip the airport kiosk queue. Apply a few days ahead; passport 6+ months valid.</p><h2>Visa on arrival</h2><p>Bought at a bank counter in arrivals (often cash, major currency) before passport control. Suits spontaneous travellers but means queueing twice.</p><h3>FAQ</h3><p><strong>Visa needed?</strong> Yes. <strong>Which is better?</strong> e-Visa = more certainty; VoA = last-minute flexibility.</p>',
 'egypt','Egypt visa guide','Compare Egypt\'s e-Visa and visa on arrival for UK travellers — how each works and which suits your trip.','egypt evisa vs visa on arrival'],
'kenya-eta-how-to-apply' => ['Kenya eTA for UK Citizens: How to Apply',
 'UK citizens must obtain an electronic travel authorisation (eTA) before travelling to Kenya — it has replaced the visa for most visitors. Apply online via the official portal, upload a passport scan and photo, pay the fee, and receive your approved eTA by email to present on arrival.',
 '<h2>What it is</h2><p>A digital entry permit for short visits, linked to your passport, mandatory for British travellers (the old visa-on-arrival is phased out). Passport 6+ months valid.</p><h2>How to apply</h2><p>On the official eTA site: enter passport + travel + accommodation details, upload a clear passport scan + photo, answer the questions, pay. Allow a few days; print the approval. One eTA per traveller incl. children.</p><h3>FAQ</h3><p><strong>eTA needed?</strong> Yes. <strong>How long?</strong> Usually a few days — apply early.</p>',
 'kenya','Kenya eTA guide','How UK citizens apply for Kenya\'s electronic travel authorisation (eTA) — the steps, documents and timing.','kenya eta for uk citizens'],
'tanzania-evisa-how-to-apply' => ['Tanzania e-Visa for UK Travellers: How to Apply',
 'UK travellers need a visa for Tanzania and can apply for an e-Visa online before departure. Complete the application on the official immigration portal, upload your passport and photo, pay the fee, and receive an approved e-Visa by email. The single-entry tourist e-Visa lets you arrive pre-approved.',
 '<h2>What it is</h2><p>An electronic visa obtained in advance via the official system, covering mainland + Zanzibar (Zanzibar requires separate mandatory travel insurance). Passport 6+ months valid.</p><h2>How to apply</h2><p>On the official portal: personal + passport + travel details, upload passport scan + photo, possibly a return ticket, pay. Processing can take several working days — apply ~2 weeks ahead; print the grant.</p><h3>FAQ</h3><p><strong>Visa needed?</strong> Yes. <strong>How long?</strong> Several working days — apply early.</p>',
 'tanzania','Tanzania visa guide','A step-by-step guide for UK travellers applying for the Tanzania e-Visa online — documents, timing and tips.','tanzania evisa for uk travellers'],
'sri-lanka-eta-explained' => ['Sri Lanka ETA for UK Citizens Explained',
 'UK citizens need an Electronic Travel Authorisation (ETA) to visit Sri Lanka for tourism. Apply online before departure via the official system with passport and travel details, and pay the fee. Once approved, the ETA is linked to your passport and allows a short tourist stay, confirmed on arrival.',
 '<h2>What it is</h2><p>A pre-travel authorisation for short visits, tied to the passport you apply with, mandatory for British travellers. Passport 6+ months valid; for tourism, not work.</p><h2>How to apply</h2><p>On the official ETA site: passport + travel details, pay. Approval is often quick (sometimes within a day) but apply ahead; print the approval. Ensure the passport number matches exactly.</p><h3>FAQ</h3><p><strong>ETA needed?</strong> Yes. <strong>How quick?</strong> Often within a day — but apply ahead.</p>',
 'sri-lanka','Sri Lanka ETA guide','What the Sri Lanka ETA is, how UK citizens apply and what to expect on arrival, in plain English.','sri lanka eta for uk citizens'],
'vietnam-visa-free-vs-evisa' => ['Vietnam Visa-Free vs e-Visa for UK Travellers',
 'UK travellers can enter Vietnam visa-free for stays of up to 45 days — short trips need only a valid passport. For longer visits or more flexibility, the Vietnam e-Visa is applied for online in advance. The right choice depends mainly on how long you stay and your entry needs.',
 '<h2>Visa-free (45 days)</h2><p>Arrive with a passport valid 6+ months + onward-travel proof; immigration admits you for the exemption period. Easiest + cheapest for most holidays. Confirm the allowance before booking.</p><h2>e-Visa</h2><p>For longer stays or multiple entries: apply online via the official portal, upload photo + passport scan, pay, receive by email to print.</p><h3>FAQ</h3><p><strong>Visa-free?</strong> Yes, up to 45 days. <strong>When the e-Visa?</strong> Longer stays or multiple entries.</p>',
 'vietnam','Vietnam visa guide','Compare Vietnam\'s 45-day visa-free entry and the e-Visa for UK travellers to pick the right option.','vietnam visa-free vs evisa'],
'etias-for-uk-citizens' => ['ETIAS for UK Citizens: When It Starts & What to Expect',
 'ETIAS is a forthcoming European travel authorisation UK citizens will need before short Schengen visits. It is not a visa but an online pre-screening linked to your passport, expected after the EU Entry/Exit System launches. You will apply online, pay a small fee, and get approval valid for multiple trips.',
 '<h2>What it is</h2><p>A visa-waiver authorisation for visa-exempt nationals (incl. British). It does not change the 90-in-180-day rule — just adds a quick online check. Once granted, valid several years / until passport expiry, for multiple trips.</p><h2>When it starts</h2><p>Introduced alongside the EU Entry/Exit System; the date has shifted and it is not yet mandatory. Until then, UK citizens travel under current rules. Check the latest timeline.</p><h3>FAQ</h3><p><strong>Is it a visa?</strong> No — an authorisation. <strong>Mandatory yet?</strong> Not yet; check the confirmed start date.</p>',
 'schengen','Schengen travel guide','What ETIAS means for UK citizens visiting the Schengen area, when it starts and how the online authorisation will work.','etias for uk citizens'],
];
foreach ( $g as $slug => $d ) {
	$content = '<p style="font-size:18px;font-weight:500;background:#EEF3FA;padding:14px 18px;border-radius:8px">' . $d[1] . '</p>' . $d[2]
		. '<p>For current entry rules + fees, see our <a href="/ukvisa/' . $d[3] . '/">' . $d[4] . '</a>.</p>';
	$e = get_page_by_path( $slug, OBJECT, 'page' );
	$arr = [ 'post_type' => 'page', 'post_name' => $slug, 'post_title' => $d[0], 'post_content' => $content, 'post_status' => 'publish' ];
	if ( $e ) { $arr['ID'] = $e->ID; $id = $e->ID; wp_update_post( $arr ); } else { $id = wp_insert_post( $arr ); }
	update_post_meta( $id, 'rank_math_title', $d[0] );
	update_post_meta( $id, 'rank_math_description', $d[5] );
	update_post_meta( $id, 'rank_math_focus_keyword', $d[6] );
	echo "$slug -> #$id\n";
}
