<?php
// Publish 6 new outbound-travel guides + RankMath meta. Run via wp eval-file.
// slug => [title, summary, body_html, money-slug-or-empty, anchor, meta-description, focus-keyword]
$g = [
'cambodia-evisa-for-uk-citizens' => ['Cambodia e-Visa for UK Citizens: How to Apply',
 'UK citizens need a visa for Cambodia and can apply for a tourist e-Visa online before they travel. You complete the application on the official portal, upload a passport scan and photo, pay, and receive an approved e-Visa by email to print and present on arrival. We are an independent service that helps you prepare and check the application — not a government website, and our service fee is separate from the government visa fee.',
 '<h2>What it is</h2><p>The Cambodia e-Visa is an electronic tourist visa, typically allowing a single entry for a short stay. It is linked to the passport you apply with, so your passport details must match exactly. Your passport should usually be valid for at least 6 months beyond your arrival date with a blank page. Always apply via the official Cambodian government portal; e-Visa is generally accepted at the main international airports and some land crossings, so check the latest list before booking.</p><h2>How to apply</h2><p>Enter your personal, passport and travel details, upload a clear passport scan and a recent photo, then pay. Approval is often issued within a few working days, but timing is not guaranteed, so apply well ahead of travel. If you choose an express handling tier with us, that speeds up <em>our</em> preparation and checking — it does not make the government decide faster or guarantee approval. Print two copies of the approved e-Visa.</p><h3>FAQ</h3><p><strong>Do UK citizens need a visa?</strong> Yes — a tourist visa, available as an e-Visa. <strong>How long does it take?</strong> Often a few working days; apply early. <strong>Is it a physical visa?</strong> You receive a printable e-Visa approval to show on arrival.</p>',
 '','UK eVisa & travel authorisation help','How UK citizens apply for the Cambodia tourist e-Visa online — documents, timing and what to expect on arrival.','cambodia evisa for uk citizens'],

'bali-indonesia-voa-vs-evoa-uk' => ['Indonesia (Bali) Visa on Arrival vs e-VOA for UK Travellers',
 'UK travellers visiting Indonesia, including Bali, normally need a visa on arrival (VOA) for tourism, and can either buy it at the airport or arrange an electronic e-VOA online before departure. Both cover a short tourist stay and can usually be extended once. We are an independent service that helps you prepare the e-VOA — not a government website, and our service fee is separate from the official VOA fee.',
 '<h2>Visa on arrival (VOA)</h2><p>You buy the VOA at a payment counter after landing, before immigration. It typically allows a short tourist stay and can usually be extended once for a similar period at a local immigration office. Your passport should be valid for at least 6 months from arrival, and you may be asked for onward-travel proof. Queues at the airport counter can be long at busy times.</p><h2>e-VOA (online)</h2><p>The e-VOA is the same permission arranged in advance via the official Indonesian portal: you enter passport and travel details, pay, and receive an approved e-VOA by email to show on arrival — letting you skip the payment counter. Apply a few days ahead. Note Indonesia also requires the separate electronic customs declaration and may require a tourism levy in Bali; check the latest rules before you travel.</p><h3>FAQ</h3><p><strong>Which is better?</strong> e-VOA saves queueing; VOA suits last-minute trips. <strong>Can I extend?</strong> Usually once, at immigration. <strong>Passport validity?</strong> Typically 6+ months.</p>',
 '','UK eVisa & travel authorisation help','Compare Indonesia\'s visa on arrival and e-VOA for UK travellers to Bali — how each works and which to choose.','indonesia bali voa vs evoa uk'],

'saudi-arabia-tourist-evisa-uk' => ['Saudi Arabia Tourist eVisa for UK Citizens',
 'UK citizens can apply for a Saudi Arabia tourist eVisa online before they travel, usually issued as a multiple-entry visa valid for one year with stays of up to 90 days. You apply via the official portal with passport details and a photo, pay, and receive the eVisa by email. We are an independent service that helps you prepare and check the application — not a government website, and our service fee is separate from the government visa fee.',
 '<h2>What it is</h2><p>The Saudi tourist eVisa is an electronic visa for tourism, family visits and certain events, and it includes mandatory medical insurance bundled into the application. It is typically multiple-entry, valid for one year, with a maximum stay of around 90 days in total. It is linked to the passport you apply with, which should usually be valid for at least 6 months. Always apply through the official Saudi portal.</p><h2>How to apply</h2><p>Complete the online form, upload a recent photo, confirm your details and pay the visa plus insurance fee. Approval is often quick, sometimes within minutes to a few days, but it is not guaranteed and timing can vary, so apply ahead. If you use an express tier with us, that speeds up <em>our</em> handling and checks — it does not make the Saudi authorities approve faster or guarantee a grant. Save and print the eVisa.</p><h3>FAQ</h3><p><strong>Is insurance included?</strong> Yes — medical cover is bundled into the eVisa fee. <strong>How long is it valid?</strong> Typically one year, multiple entry, up to ~90 days per visit. <strong>Is approval guaranteed?</strong> No — always apply early.</p>',
 '','UK eVisa & travel authorisation help','How UK citizens apply for the Saudi Arabia tourist eVisa online — validity, bundled insurance and timing.','saudi arabia tourist evisa uk'],

'oman-evisa-for-uk-travellers' => ['Oman eVisa for UK Travellers: What to Know',
 'UK travellers heading to Oman may need an eVisa for tourism, applied for online before departure, though short-stay visa-free entry has applied for some nationalities at times — so always check the latest rules. When required, you apply on the official portal with passport details and a photo, pay, and receive an approved eVisa by email to present on arrival. We are an independent service that helps you prepare the application — not a government website, and our service fee is separate from any government fee.',
 '<h2>What it is</h2><p>The Oman eVisa is an electronic entry permit for tourism, typically issued for a short single stay, with longer-validity options also available. Entry rules for Oman have changed in recent years, including periods of visa-free short stays for certain visitors, so confirm whether you need an eVisa for your trip before booking. Your passport should usually be valid for at least 6 months beyond arrival.</p><h2>How to apply</h2><p>On the official Royal Oman Police eVisa portal, enter your passport and travel details, upload a photo and any required documents, then pay. Processing is often a few working days but is not guaranteed, so apply well ahead. An express tier with us speeds up <em>our</em> preparation and checks only — it does not speed up or guarantee the government decision. Print the approved eVisa to show on arrival.</p><h3>FAQ</h3><p><strong>Do I always need one?</strong> Not always — rules change; check the latest before travel. <strong>How long does it take?</strong> Often a few working days; apply early. <strong>Passport validity?</strong> Typically 6+ months.</p>',
 '','UK eVisa & travel authorisation help','What UK travellers should know about the Oman eVisa — when it is needed, how to apply and timing.','oman evisa for uk travellers'],

'canada-eta-for-uk-citizens' => ['Canada eTA for UK Citizens Explained',
 'UK citizens flying to or transiting through Canada normally need an Electronic Travel Authorisation (eTA) before they board. An eTA is an authorisation linked to your passport — not a visa or a physical document — and it lets visa-exempt travellers fly to Canada for short visits. You apply online via the official portal, pay a small fee, and most approvals arrive quickly by email. We are an independent service that helps you complete and check the application — not a government website, and our service fee is separate from the government fee.',
 '<h2>What it is</h2><p>The Canada eTA is required for visa-exempt nationals, including British citizens, arriving by air; it is generally not needed for entry by land or sea. It is electronically linked to the passport you apply with and is typically valid for up to five years or until that passport expires, allowing multiple short visits. It does not guarantee entry — the final decision rests with a border officer.</p><h2>How to apply</h2><p>Apply on the official Government of Canada eTA site: enter your passport, contact and travel details, answer the eligibility questions and pay. Many approvals come within minutes, but some take longer if a review is needed, so apply before you book non-refundable travel. An express tier with us speeds up <em>our</em> handling only — it cannot make Canada decide faster or guarantee approval.</p><h3>FAQ</h3><p><strong>Is it a visa?</strong> No — it is an authorisation tied to your passport. <strong>How long valid?</strong> Up to five years or passport expiry. <strong>Needed for driving across the border?</strong> Generally only required for air travel.</p>',
 '','UK eVisa & travel authorisation help','What the Canada eTA is for UK citizens, how it works and how to apply online before flying.','canada eta for uk citizens'],

'new-zealand-nzeta-ivl-uk' => ['New Zealand NZeTA & IVL for UK Travellers',
 'UK travellers visiting New Zealand normally need an NZeTA (New Zealand Electronic Travel Authority) before they travel, and most pay the International Visitor Conservation and Tourism Levy (IVL) at the same time. The NZeTA is an authorisation linked to your passport — not a visa label — and lets visa-waiver visitors enter for short stays. You apply online, pay, and receive confirmation by email. We are an independent service that helps you prepare the application — not a government website, and our service fee is separate from the government NZeTA and IVL charges.',
 '<h2>What it is</h2><p>The NZeTA is required for visa-waiver travellers, including British citizens, and for those transiting through Auckland. It is linked to the passport you apply with and is typically valid for up to two years for multiple short visits. The IVL is a separate conservation and tourism levy usually paid together with the NZeTA. Your passport should generally be valid for at least 3 months beyond your planned departure from New Zealand.</p><h2>How to apply</h2><p>Apply via the official Immigration New Zealand channel (website or app): enter passport and travel details, pay the NZeTA fee plus the IVL, and submit. Processing can take up to around three days, though it is often faster — apply at least a few days before travel and never assume instant approval. An express tier with us speeds up <em>our</em> preparation only; it does not change the government processing time or guarantee approval.</p><h3>FAQ</h3><p><strong>Do I need both?</strong> Most visitors pay the NZeTA and the IVL together. <strong>Is it a visa?</strong> No — an authorisation tied to your passport. <strong>How long valid?</strong> Usually up to two years.</p>',
 '','UK eVisa & travel authorisation help','What UK travellers need to know about New Zealand\'s NZeTA and the IVL levy — how they work and how to apply.','new zealand nzeta ivl uk'],
];
foreach ( $g as $slug => $d ) {
	$money = $d[3] !== '' ? '/ukvisa/' . $d[3] . '/' : '/ukvisa/';
	$content = '<p style="font-size:18px;font-weight:500;background:#EEF3FA;padding:14px 18px;border-radius:8px">' . $d[1] . '</p>' . $d[2]
		. '<p>For more help with your application, see our <a href="' . $money . '">' . $d[4] . '</a>. Independent service — not a government website.</p>';
	$e = get_page_by_path( $slug, OBJECT, 'page' );
	$arr = [ 'post_type' => 'page', 'post_name' => $slug, 'post_title' => $d[0], 'post_content' => $content, 'post_status' => 'publish' ];
	if ( $e ) { $arr['ID'] = $e->ID; $id = $e->ID; wp_update_post( $arr ); } else { $id = wp_insert_post( $arr ); }
	update_post_meta( $id, 'rank_math_title', $d[0] );
	update_post_meta( $id, 'rank_math_description', $d[5] );
	update_post_meta( $id, 'rank_math_focus_keyword', $d[6] );
	echo "$slug -> #$id\n";
}
